language: java

sudo: false # faster builds

jdk:
  - openjdk8

script:
  - ./mvnw clean verify -B -V

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - bash <(curl -s https://codecov.io/bash)
  - ./mvnw coveralls:report
